/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/footer/footer.vue')['default']
    NutCountdown: typeof import('@nutui/nutui-taro')['Countdown']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutImage: typeof import('@nutui/nutui-taro')['Image']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutPrice: typeof import('@nutui/nutui-taro')['Price']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
  }
}
